//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication19.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENROLL_STUDENT_CLASS
    {
        public int STUDENT_ID { get; set; }
        public int CLASS_ID { get; set; }
        public int ENROL_STU_CLASS_ID { get; set; }
    }
}
