//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication19.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENROLL_PAY
    {
        public int PAY_ID { get; set; }
        public Nullable<int> PAID_ID { get; set; }
        public Nullable<int> STUDENT_ID { get; set; }
        public Nullable<int> PAY { get; set; }
        public Nullable<int> STAFF_ID { get; set; }
        public Nullable<System.DateTime> TIMESTAMP { get; set; }
    }
}
