//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication19.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENROLL_PAID
    {
        public int PAID_ID { get; set; }
        public Nullable<int> STUDENT_ID { get; set; }
        public Nullable<int> MONTHLY_ID { get; set; }
        public Nullable<System.DateTime> TIMESTAMP { get; set; }
        public Nullable<int> STAFF_PAID_ID { get; set; }
        public Nullable<int> STUDENT_TYPE_ID { get; set; }
        public Nullable<int> PAID { get; set; }
        public Nullable<int> CLASS_ID { get; set; }
        public Nullable<int> PAY_ID { get; set; }
    }
}
