//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication19.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FOOD
    {
        public int FOOD_ID { get; set; }
        public string FOOD_ID_STUDENT { get; set; }
        public string FOOD_NAME { get; set; }
        public string FOOD_LASTNAME { get; set; }
        public string FOOD_MONTH_TH { get; set; }
        public string FOOD_MONTH_INDEX { get; set; }
        public Nullable<int> FOOD_PAID { get; set; }
        public Nullable<int> FOOD_FULL_PAID { get; set; }
        public string FOOD_CLASS { get; set; }
        public string FOOD_YEAR { get; set; }
        public Nullable<System.DateTime> FOOD_TIMESATAMP { get; set; }
        public string FOOD_UPDATE { get; set; }
        public Nullable<int> FOOD_PAID_ID { get; set; }
        public string FOOD_TITLE { get; set; }
    }
}
