//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication19.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MONTHLY
    {
        public int MONTHLY_ID { get; set; }
        public string MONTH_NAME { get; set; }
        public Nullable<int> MONTH_YEAR { get; set; }
        public Nullable<int> MONTH_COURSE { get; set; }
        public Nullable<bool> MONTH_STATUS { get; set; }
        public Nullable<int> MONTH_YEARINDEX { get; set; }
    }
}
