//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication19.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUDENTS
    {
        public int STUDENT_ID { get; set; }
        public string STUDENT_TITLE { get; set; }
        public string STUDENT_NAME { get; set; }
        public string STUDENT_LNAME { get; set; }
        public Nullable<System.DateTime> STUDENT_BIRTHDAY { get; set; }
        public string STUDENT_IDCARD { get; set; }
        public Nullable<int> STUDENT_PSIS_ID { get; set; }
        public string STUDENT_STATUS { get; set; }
        public Nullable<System.DateTime> STUDENT_TIMESTAMP { get; set; }
    }
}
